support/log: rename ``__log`` to ``__do_log``
No functional changes.  To avoid declaration conflicts below, rename it.

/usr/local/include/vfn/support/log.h:57:56: error: conflicting declaration of C function ‘void __log(int, const char*, ...)’
   57 | static inline void __attribute__((format(printf, 2, 3))) __log(int v, char const *fmt, ...)
      |                                                        ^~~~~
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:104:61: note: previous declaration ‘double __log(double)’
  104 | __MATHCALL_VEC (log,, (_Mdouble_ __x));
      |                                                             ^

Signed-off-by: Minwoo Im <minwoo.im@samsung.com>